name: Fetch and Predict Penguin Species

on:
  schedule:
    - cron: '30 7 * * *'  # Runs every day at 7:30 AM UTC
    
jobs:
  fetch_and_predict:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Files Exist (Debugging Step)
        run: ls -l

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Prediction Script
        run: python src/predict_penguin.py

      - name: Commit and Push JSON Prediction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/penguin_prediction.json
          git commit -m "Updated prediction data" || echo "No changes to commit"
          git push origin main
